/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import javax.swing.UIManager;

/**
 *
 * @author sridhar
 */
public class moveFile extends javax.swing.JFrame {

    /**
     * Creates new form moveFile
     */
    public moveFile()
    {
        initComponents();
        setLocation(250, 250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        source = new javax.swing.JTextField();
        target = new javax.swing.JTextField();
        sourceButton = new javax.swing.JButton();
        targetButton = new javax.swing.JButton();

        setTitle("Move");

        sourceButton.setText("from");
        sourceButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sourceButtonActionPerformed(evt);
            }
        });

        targetButton.setText("To");
        targetButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                targetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sourceButton)
                    .addComponent(targetButton))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(source)
                    .addComponent(target, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(target, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(targetButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void targetButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_targetButtonActionPerformed
    {//GEN-HEADEREND:event_targetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetButtonActionPerformed

    private void sourceButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sourceButtonActionPerformed
    {//GEN-HEADEREND:event_sourceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception e)        {
            System.out.println("Error setting native LAF: " + e);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new moveFile().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField source;
    private javax.swing.JButton sourceButton;
    private javax.swing.JTextField target;
    private javax.swing.JButton targetButton;
    // End of variables declaration//GEN-END:variables
}
